# Generated by Django 6.0 on 2025-12-31 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(default='Class 12', max_length=20)),
                ('stream', models.CharField(choices=[('science-maths', 'Science (Maths)'), ('science-bio', 'Science (Biology)'), ('commerce', 'Commerce'), ('arts', 'Arts')], max_length=50)),
                ('phone', models.CharField(help_text='Student phone number', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
